### ISSUE TITLE
Select Bootstrap + Perfect scrollbar

### ISSUE THREAD

**Issue by rem42** [creativetimofficial/ct-now-ui-dashboard-pro#12]
Hi,

When i use "selectpicker" with a lot of options in select, the scroll bar doesn't work.

As you can test/see on your demo : https://demos.creative-tim.com/now-ui-dashboard-pro/examples/forms/extended.html
With the second select in "Customisable Select".

The scroll with the mouse wheel doesn't work on it, but only the entire window.

Windows 10 + Chrome.

Thx.

ps : Sorry, for my bad english.

**Comment by dragosct** [comment]
Hi, @rem42! Thank you for using our product. We will check this issue and we will come with an answer. Regards, Dragos

**Comment by dragosct** [comment]
Hi, @rem421! Sorry for the late response. I don't know if you fix this issue, but I saw that the issue is common also for the silvio moreto plugin, so please check this[ link](https://github.com/silviomoreto/bootstrap-select/issues/658) and here you will find also a solution. Regards, Dragos
