### ISSUE TITLE
How to apply fixed-bottom on footer without make it overlap with sidebar?

### ISSUE THREAD

**Issue by hbinduni** [creativetimofficial/ct-now-ui-dashboard-pro#13]
Hi, i use your default footer example like below:

```
<footer class="footer">
  <div class="container-fluid">
    <nav>
      <ul>
        <li>
          <a href="/">
            Home
          </a>
        </li>
        <li>
          <a href="/about-us">
            About Us
          </a>
        </li>
      </ul>
    </nav>
    <div class="copyright">
      Copyright &copy; 2018. XYZ, Inc.
    </div>
  </div>
</footer>
```

but when i apply fixed-bottom on footer, the footer and sidebar navigation become overlap. i can not see the button link home and about as shown below.

Can you tell me how can i show the button link or make the footer not overlap with sidebar?

<img width="971" alt="screenshot 2018-03-21 16 42 00" src="https://user-images.githubusercontent.com/1378410/37703038-ea9bd87c-2d26-11e8-9e7f-869fa1e5b364.png">

**Comment by dragosct** [comment]
Hi, @hbinduni! Thank you for using our product. Please, tell us if you want to use the footer with that class `.fixed-bottom`? Regards, Dragos

**Comment by hbinduni** [comment]
Yes, we want to use `.fixed-bottom`
But can you tell us how to make `footer` with `.fixed-bottom` not overlap with sidebar?

**Comment by dragosct** [comment]
Hi! Please try to use these properties from below: 

<img width="783" alt="screen shot 2018-03-22 at 11 11 55" src="https://user-images.githubusercontent.com/17456857/37761302-f327c2e4-2dc1-11e8-9bde-e3e187411412.png">

Hope this will help you! 

Regards, 
Dragos

**Comment by hbinduni** [comment]
Hi, i use this one already, but as you can see below, the sidebar become overlap with footer. 
How can i use .fixed-bottom but not make my sidebar overlap with footer?

<img width="1499" alt="screenshot 2018-03-22 16 19 01" src="https://user-images.githubusercontent.com/1378410/37761672-e6ee52c4-2dec-11e8-8224-d3a8ae10f29b.png">

**Comment by dragosct** [comment]
Hi, @hbinduni! Please watch more carefully in the image that I uploaded the class .footer have the properties:

```css
width: calc(100% - 80px);
margin-left: auto;
```

Regards,
Dragos
