### ISSUE TITLE
Menu not intuitive on mobile

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-now-ui-dashboard-pro#17]
Hi, I don't know if you have tried the template on a mobile device with the proportions to support the same design as the computer (Example an iPad), but the menu is not very intuitive.

In fact, we can move the menu, from left to right when it is minimized, when we manage to open it completely we can not close it with the button, you have to click next to it.

I think it would be nice to activate the version for smaller screens on all mobile devices, since they cannot pass their mouse over them, since they do not have one!

![menu](https://user-images.githubusercontent.com/27307704/40308026-d163363a-5cd2-11e8-977a-5e53df5a52a3.gif)

Regards

**Comment by dragosct** [comment]
Hi, @KonScyence! Nice, thank you for this issue. We will fix this in the next update which will be these days. Regards, Dragos
