### ISSUE TITLE
Scroll bar visible in table

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-now-ui-dashboard-pro#18]
Hi, I think the scrollbar should not be there if there is nothing to scroll.
I think CSS should be like this:
```
.table-responsive {
    overflow-x: auto;
}
```

And not like this:
```
.table-responsive {
    overflow: scroll;
}
```

![scroll](https://user-images.githubusercontent.com/27307704/40455625-dce7c170-5ebb-11e8-8d20-66ca3fca9072.PNG)

Regards

**Comment by dragosct** [comment]
Hi, @KonScyence! Thank you for your observation, we will fix this in the next update which will be this week. Regards, Dragos
