### ISSUE TITLE
firefox and now ui icons

### ISSUE THREAD

**Issue by pmm1899** [creativetimofficial/ct-now-ui-dashboard-pro#19]
Hi, if I open any page with Firefox (quantum 61.0b8 (64-bit)), I don't see now UI icons. But with IE i can see them right.

![1](https://user-images.githubusercontent.com/12805908/40579345-ccd65fca-60fb-11e8-99c1-68585c782cc0.PNG)

Any thoughts? thanks

**Comment by dragosct** [comment]
Hi, @pmm1899! Thank you for using our product. Please, can you tell us if which OS do you have because I tested on macOS and also on windows and the icons are working fine? Regards, Dragos

**Comment by pmm1899** [comment]
Hi Dragos, its working now. Thanks. Regards.
