### ISSUE TITLE
BS datetime-picker issues

### ISSUE THREAD

**Issue by pmm1899** [creativetimofficial/ct-now-ui-dashboard-pro#20]
Hi, i have two issues with BS datetime-picker:

1) when i use it inside modal, it shows with very low opacity as you can see in my attach.
I think that if there is not enough space to show pickers modal, then it opens with very low opacity.

![1](https://user-images.githubusercontent.com/12805908/40579393-aaa5dc40-60fc-11e8-8814-22146ef42f53.PNG)

2) I also can't see any icons

![2](https://user-images.githubusercontent.com/12805908/40579432-7679cfa2-60fd-11e8-8959-2fc90d40ab32.png)

Thanks.

**Comment by pmm1899** [comment]
Issue number 2 is solved now. I forgot to call demo.initDateTimePicker() from demo.js

**Comment by timcreative** [comment]
Hi, @pmm1899! Please take the latest version of the product, the issue it's fixed now. Regards, Dragos
