### ISSUE TITLE
Sidebar Mini

### ISSUE THREAD

**Issue by Viper7171** [creativetimofficial/ct-now-ui-dashboard-pro#24]
How do I keep the sidebar mini activated (or how ever I want it) on all my pages. It starts normal then I activate it, then when I navigate to another page it is deactivated again. How do I keep it consistent throughout my whole web site.

I'm using ASP.NET MVC 5 with layout page.

Thanks,
Dave

**Comment by dragosct** [comment]
Hi, @Viper7171! Thank you for using our product. You just have to put the class `.sidebar-mini` on the body tag. Regards, Dragos
