### ISSUE TITLE
Bug with the sidebar

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-now-ui-dashboard-pro#25]
Hi, with the version that we download, when we first click on the button to enlarge the menu, it does not work ...

![sidebarbug](https://user-images.githubusercontent.com/27307704/41604431-3e2786cc-73ad-11e8-999d-9dafff01e756.gif)

Regards!

**Comment by dragosct** [comment]
Hi, @KonScyence! Please try to put in the now-ui-dashboard.js file the next code. This will fix the issue and we will put also in the next update. 

```js
$(document).ready(function(){
    if($('body').hasClass('sidebar-mini')){
       sidebar_mini_active = true
     }
});

```

Regards,
Dragos
