### ISSUE TITLE
Input with icon

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-now-ui-dashboard-pro#26]
Hi, we can see an error with field with icons in the documentation:
![iconform](https://user-images.githubusercontent.com/27307704/41604815-17b9e6a0-73ae-11e8-8352-c318df2e38f6.PNG)

Regards!

**Comment by dragosct** [comment]
Hi, @KonScyence! Thank you for your observation. This problem exists because the bootstrap version was changed in the latest update and we don't update the code for the inputs in the docs, in the product everything is working fine. We will fix this minor issue in the next update. Regards, Dragos
