### ISSUE TITLE
Proposal for dropdown-menu

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-now-ui-dashboard-pro#27]
Hi, I think it might be a good idea to use perfect scrollbar in dropdown menus to match the rest of the template:
Example: [http://klam.shost.ca/test/](http://klam.shost.ca/test/)

JS added:
```
$(function() {
  $(".ps-scrollbar-y").on("click", function(a) {
    a.stopPropagation();
  });
  $(".dropdown-menu.inner").perfectScrollbar();
  $("body").on("shown.bs.dropdown", function() {
    $(".dropdown-menu.inner").perfectScrollbar("update");
  });
});
```

CSS added:
```
.dropdown-menu {
   padding: 0.2rem 0 0.2rem 0 !important;
}

.bootstrap-select.btn-group .dropdown-menu.inner {
	position: relative;
}
```

P.S. Do you have a solution to remove the scrollbar when it's not necessary?
![scrolldropdown](https://user-images.githubusercontent.com/27307704/41797148-eeaa0246-7636-11e8-93c0-b1c79ea9e75e.PNG)

Regards!

**Comment by dragosct** [comment]
Hi, @KonScyence! Thank you for your suggestion. We will analyze this suggestion and if everything is ok we will add in the next update. 

Regards, 
Dragos

**Comment by KonScyence** [comment]
Hi @dragosct10, I think you forgot something in v 1.1.1, because this is not normal:
![bugselectperfectscroll](https://user-images.githubusercontent.com/27307704/42830791-7a2251b6-89ba-11e8-9c35-39ef019b5512.gif)

I tried to correct the error myself, but I have the impression that you have changed a lot of things in the css file, I don't find myself anymore ^^. With version 1.1.0, my above correction was working.

Regards

**Comment by dragosct** [comment]
Hi, @KonScyence! Yes, you are right about this. In the last version, we updated the select picker to the latest version and this is the reason for the problem. We have to see how to fix it and we will come back with an answer for you. 

Regards, 
Dragos
