### ISSUE TITLE
Form Wizard Bug Image Upload

### ISSUE THREAD

**Issue by justinledelson** [creativetimofficial/ct-now-ui-dashboard-pro#29]
When the image upload module from the extended forms is added to a tab in the wizard it breaks the view switching.

Please see video demonstration.
http://cloud.codecowboy.com/3W1J3D2x2Y3M

**Comment by dragosct** [comment]
Hi, @justinledelson! Thank you for using our product. Please tell me if you use the latest version of the product? Regards, Dragos

**Comment by justinledelson** [comment]
@dragosct10 yes I am on v1.1.0

**Comment by dragosct** [comment]
Hi, @justinledelson! Sorry for the late response. I just reproduce the issue and I want to figure out the source of the problem and the problem is coming from the plugin of the [wizard](http://github.com/VinceG/twitter-bootstrap-wizard) who is not compatible with bs4 so this is the main problem here. We must replace this plugin with another this is the fix because this plugin will not be updated anymore for the BS 4 version so we are sorry for this inconvenience and we will come back to you with an update in a couple of days. 

Regards, 
Dragos

**Comment by dragosct** [comment]
Hi, @justinledelson! Sorry for the late response. Regard to your problem we found that the jasny library it's not compatible with the wizard library so we made for you a custom code for the file upload and please to make it work follow the next steps: 

1. First take the file upload scss partial and go to your project in `assets/scss/now-ui-dashboard/plugins/` and replace with this partial. 
[_plugin-jasny-fileupload.scss.zip](https://github.com/creativetimofficial/ct-now-ui-dashboard-pro/files/2183560/_plugin-jasny-fileupload.scss.zip)

2. Please remove this line of code from the end of the page.
```js
<script src="../../assets/js/plugins/jasny-bootstrap.min.js"></script>
```

3. Take the js code from below and go in the `now-ui-dashboard.js` in the ready function and put inside: 
```js
  // FileInput
  $('.form-file-simple .inputFileVisible, .form-file-simple .fileinput-exists').click(function(){
      $(this).siblings('.inputFileHidden').trigger('click');
  });

  $('.form-file-simple .img-preview').on('load', function() {
    $('.form-file-simple .fileinput-new, .form-file-simple .inputFileVisible').addClass('fileinput-none');
    $('.form-file-simple .btn-file, .form-file-simple .fileinput-remove').removeClass('fileinput-none');
  });

  $('.form-file-simple .inputFileHidden').change(function() {
      var filename =  $(this).val().replace(/C:\\fakepath\\/i, '');
      $(this).siblings('.inputFileVisible').val(filename);
  });
  $('.form-file-simple .fileinput-remove').click(function() {
      $(this).parent('.fileinput-wrapper').siblings('.thumbnail').find('.img-preview').attr('src', '#');
      $(this).siblings('.inputFileHidden, .inputFileVisible').val('');
      $('.form-file-simple .btn-file, .form-file-simple .fileinput-remove').addClass('fileinput-none');
      $('.form-file-simple .fileinput-new, .form-file-simple .inputFileVisible').removeClass('fileinput-none');
  });
``` 

and this function outside of the ready function: 

```js
function readURL(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();
    reader.onload = function (e) {
      $('#image').attr('src', e.target.result);
    };
    reader.readAsDataURL(input.files[0]);
  }
}
```

4. Go to the wizard page and inside wizard code in html please add the following code: 

```html
<div class="fileinput form-file-upload form-file-simple">
         <div class="fileinput-new thumbnail">
                 <img src="../../assets/img/dashboard/pro/image_placeholder.jpg" alt="...">
         </div>
         <div class="fileinput-preview thumbnail">
                  <img id="image" src="#" alt="" class="img-preview">
         </div>
         <div class="fileinput-wrapper">
                  <span class="btn btn-rose btn-round btn-file fileinput-none">
                             <span class="fileinput-exists">Change</span>
                              <input type="file" name="..." onchange="readURL(this);"/>
                   </span>
                   <a href="#pablo" class="btn btn-danger btn-round fileinput-remove fileinput-none"><i class="fa fa-times"></i> Remove</a>
                    <button class="btn btn-round inputFileVisible">Select image</button>
                    <input type="file" class="inputFileHidden" onchange="readURL(this);">
           </div>
</div>
```

Please let us know if everything is working fine! 

Regards, 
Dragos

**Comment by justinledelson** [comment]
This fixed the issue. Thanks!
