### ISSUE TITLE
Problem with compiller sass

### ISSUE THREAD

**Issue by sandersonsoares** [creativetimofficial/ct-now-ui-dashboard-pro#3]
Stack: 

` error.../assets/sass/now-ui-dashboard/mixins/_badges.scss (Line 13: Mixins may not be defined within control directives or other mixins.)`

**Comment by dragosct** [comment]
Hi, @sandersonsoares! Thank you for using our product. Please, can you tell me if you made some changes in the partial _badges.scss or in the mixins folder? 

Regards, Dragos

**Comment by sandersonsoares** [comment]
I did not make any changes! seems to be a problem that sass does not compile a mixin within another one I researched. So to fix, I have separated, but I do not know if it will cause any other bug in the template. But temporarily for me to implement in my project I modified to stay like this:

**Before**
`@mixin create-colored-badges() {
@mixin badges-color($color) {
}
}`

**After**
`@mixin create-colored-badges() {}`
`@mixin badges-color($color) {}`

**Comment by dragosct** [comment]
Hi, @sandersonsoares! We will fix it in the next release. It will not affect the rest of the code. 

Regards,
Dragos
