### ISSUE TITLE
UTF8 characters in forms

### ISSUE THREAD

**Issue by jposes22** [creativetimofficial/ct-now-ui-dashboard-pro#30]
When a form with text is sent and this text has special characters such as accents or ñ, the encoding of the text does not arrive correctly to the backend.

We have tried to put the form accept-charset = "UTF-8" and it does not work either

**Comment by dragosct** [comment]
Hi, @jposes22! Thank you for using our product and sorry for the late response. I'm not sure if the problem is from our side because we don't do the part of the backend we just style the forms, but please show us an example. Regards, Dragos
