### ISSUE TITLE
Can't scroll in modal

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-now-ui-dashboard-pro#31]
Hi, I noticed that if the window of a modal was too big, we could not scroll, do you have a solution?

Example: http://klam.shost.ca/test/

Regards

**Comment by dragosct** [comment]
Hi, @KonScyence! On my side, the scroll is working fine, but I think you tried on Windows right? 

Regards, 
Dragos

**Comment by KonScyence** [comment]
Yes, here is a gif:
![modalslide](https://user-images.githubusercontent.com/27307704/42456937-184322e2-8364-11e8-812d-b23956266782.gif)

Regards

**Comment by dragosct** [comment]
Hi, @KonScyence! Please try to put this code in the now-ui-dashboard.js file like below: 

```js
$(document).ready(function(){
  var isWindows = navigator.platform.startsWith('Win');

  if(isWindows) {
    $('.modal').on('shown.bs.modal', function () {
                  console.log('shown');
                  $('.main-panel').perfectScrollbar('destroy');
              }).on('hidden.bs.modal', function (){
                  console.log('hidden');
                  $('.main-panel').perfectScrollbar();
              });
  }
});
```

**Comment by KonScyence** [comment]
Working, thanks!
