### ISSUE TITLE
other scripts not working

### ISSUE THREAD

**Issue by ap299** [creativetimofficial/ct-now-ui-dashboard-pro#32]
hey im using other plugins but its not working why??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by dragosct** [comment]
Hi, @ap299! Thank you for using our products. It can be many reasons why another plugin not working for you. Please, show us what is the problem. 

Regards, 
Dragos

**Comment by ap299** [comment]
im trying to implement checkbox in dropdownlist but online script plugin and offline script not working plz try to help

**Comment by dragosct** [comment]
Hi, @ap299! Please, tell me did you comment also on the product page in the comment section on our site and you have this id `apurvaawar`, right?
