### ISSUE TITLE
perfectScrollbar in macos

### ISSUE THREAD

**Issue by gustavotrott** [creativetimofficial/ct-now-ui-dashboard-pro#33]
Hello, 
Currently the plugin perfectScrollbar is being started just when it is running on Windows OS.
Is there any particular reason for that?

The layout is ugly in macos with the default scroll as well!

I can activate manually, but I think it would be interesting start automatically for all browsers.

Thanks,
Gustavo

**Comment by dragosct** [comment]
Hi, @gustavotrott! Thank you for using our product and for your suggestion. I understand what you said and if you want yes you can activate also on your macos with no problems, but regard on what you said to be by default activated we usually wait for the minimum 3-5 request to implement something. 

Regards, 
Dragos

**Comment by gustavotrott** [comment]
Take a look how the menu appears crooked because the scroll, mainly when the sidebar is mini.
![captura de tela 2018-07-20 as 10 54 26](https://user-images.githubusercontent.com/5660191/43006372-e9e54dfc-8c0b-11e8-9cfd-36bbec16b306.png)

should you wait for 3 requests to enable perfect scroll and fix this?

**Comment by dragosct** [comment]
Hi, @gustavotrott! It's weird because on our side the scrollbar looks nice like you can see in this [video](https://www.dropbox.com/s/c6wy95ef58athjl/now-ui-pro.mp4?dl=0). Please tell us on which os and browser did you test? In the javascript settings, we set that the perfect scrollbar must activate when the Windows Os is detected so by default should work on all browsers of Windows. 

Regards, 
Dragos

**Comment by gustavotrott** [comment]
It happens in Chrome, Firefox and Safari. All browsers I've tried.
OS: macOS High Sierra

It doesn't happen when I include the command $(".sidebar .sidebar-wrapper").perfectScrollbar() to run in any OS.

-- 
Gustavo

**Comment by dragosct** [comment]
Hi! If you add this line of code and it's working for you, this is good. We have to test it and if it's all ok we will add this to the next update. Regards, Dragos
