### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by gustavotrott** [creativetimofficial/ct-now-ui-dashboard-pro#34]
Could you include a example with a simple file input? not image!

The css and javascript are ready to have Image Upload using "FileUpload Jasny".
But I have problems when I want to include other types of file upload.

Thank you

**Comment by dragosct** [comment]
Hi, @gustavotrott! Yes, you can have also single file input with no image, but you have to follow the steps that I will show you below: 

1. Take this code and go to the `now-ui-dashboard.js` file and add this in the ready function:

```js
  // FileInput
  $('.form-file-simple .inputFileVisible').click(function(){
      $(this).siblings('.inputFileHidden').trigger('click');
  });

  $('.form-file-simple .inputFileHidden').change(function() {
      var filename =  $(this).val().replace(/C:\\fakepath\\/i, '');
      $(this).siblings('.inputFileVisible').val(filename);
  });
  $('.form-file-simple .inputFileHidden').css('z-index','-1');
```

2. In the html page please add this code: 

```html
<div class="form-group form-file-upload form-file-simple">
       <input type="text" class="form-control inputFileVisible" placeholder="Simple chooser...">
       <input type="file" class="inputFileHidden">
</div>
```

Please let us know if everything is working fine for you! 

Regards, 
Dragos
