### ISSUE TITLE
fixed navbar

### ISSUE THREAD

**Issue by peterchibunna** [creativetimofficial/ct-now-ui-dashboard-pro#36]
Is it possible to have the navbar fixed on scroll?

**Comment by dragosct** [comment]
Hi, @peterchibunna! Thank you for using our products. Yes, we will add this feature in the next update which will be in a few days. Regards, Dragos

**Comment by peterchibunna** [comment]
Ok, that's what I'm waiting for before I make a purchase.

**Comment by peterchibunna** [comment]
Hello @dragosct10, any hope yet?

**Comment by dragosct** [comment]
Hi, @peterchibunna! Sorry for the late response. Yes, today we will make this update. Regards, Dragos

**Comment by peterchibunna** [comment]
Thanks for this feature. But could you please explain what the ` color-on-scroll="20"` is and if we can use it to add bg color to a transparent navbar when you scroll up?

**Comment by dragosct** [comment]
Hi! Of course that I can explain to you. This attribute `color-on-scroll` activates the color that is applied to the navbar when you scroll the page and the value `20` it means the space between the top  0 of your window and the moment when the navbar receive that color, so with this value the navbar will receive the color white when you scroll 20px from the top to the bottom. I hope this will make sense to you.

**Comment by KonScyence** [comment]
Hi @dragosct10, what am I doing wrong here: http://klam.shost.ca/test/

Regards

**Comment by dragosct** [comment]
Hi, @KonScyence! Do you refer to the navbar fixed, right? I noticed that it's working fine, but what problem did you have? Regards, Dragos

**Comment by KonScyence** [comment]
Hello @dragosct10, there is no color on scroll when I scroll:
![scroll-top](https://user-images.githubusercontent.com/27307704/43777398-b262f83e-9a20-11e8-98e1-dfa566138b26.gif)

Regards

**Comment by dragosct** [comment]
Hi! Maybe you have some cache on your browser because please look at my [video](https://www.dropbox.com/s/uwf1j0mrkv2ox3e/color-on-scroll.mov?dl=0) to see that in our side everything is working fine. Regards, Dragos

**Comment by KonScyence** [comment]
Hi @dragosct10, it seems to not work on windows. I have just tried on windows 7 with opera 52, chrome 65 and firefox 59, and I have the same problem, but if I go on android 7.1 with the default browser, it's working... Do you know where it can come from ?

Regards

**Comment by dragosct** [comment]
We will check on windows to see where is the problem, because right now I can't have any idea, just thinking that is weird, but we will check this. Regards, Dragos

**Comment by dragosct** [comment]
Hi! Please see this issue #42 to fix the problem. 

Regards, 
Dragos
