### ISSUE TITLE
Datepicker doesn't work in documenation

### ISSUE THREAD

**Issue by BohdanKorinnyi** [creativetimofficial/ct-now-ui-dashboard-pro#4]
Hello!
DateTimePicker doesn't work on the page
![image](https://user-images.githubusercontent.com/8822555/35883948-c02703de-0b91-11e8-8632-9a77c464d4d9.png)

**Comment by sandersonsoares** [comment]
The same problem occurs to me.

**Comment by dragosct** [comment]
Hi! Yes, you have right. We will fix this in the next update which will be very soon. In the product, it works fine. Thank you. Regards, Dragos
