### ISSUE TITLE
Regular select

### ISSUE THREAD

**Issue by justinledelson** [creativetimofficial/ct-now-ui-dashboard-pro#41]
There isn't an option for a regular select.

When I try this, my select box book weird:
![image](https://user-images.githubusercontent.com/2658766/43874799-8cc47454-9b42-11e8-91c6-7c2a55070986.png)

**Comment by dragosct** [comment]
Hi! Please give us your link to your project to see what is the problem. Regards, Dragos

**Comment by justinledelson** [comment]
My mistake. I was looking at it in Chrome Dev Tools.
