### ISSUE TITLE
Different fonts Chrome vs Mozilla

### ISSUE THREAD

**Issue by raulmellado** [creativetimofficial/ct-now-ui-dashboard-pro#43]
Hi,

when I try to view the files in Chrome/Firefox, they appear slightly different (even on the demo site). I am using Windows 10, and the latest chrome/firefox.

Chrome:
https://www.screencast.com/t/XoS5sgYZCr
https://www.screencast.com/t/EXKPFJ53LA

Firefox:
https://www.screencast.com/t/WwgyRC6QzkG
https://www.screencast.com/t/U1Cz6akoBEZ

(fonts seem bolder in firefox)

Do you know why this might be?

Thanks!

**Comment by dragosct** [comment]
Hi, @raulmellado! Thank you for using our products. There are some problems with firefox anti-aliased text and please see this [link](https://support.mozilla.org/ro/questions/1167092) and maybe this will help you. 

Regards, 
Dragos
