### ISSUE TITLE
Chrome autofill styles override .form-control style

### ISSUE THREAD

**Issue by ezehnder** [creativetimofficial/ct-now-ui-dashboard-pro#44]
When using Now UI Dashboard pro, specifically the login page template with a background image, if someone chooses to have their credentials remembered on Chrome browser, the autofilled input tags are not honoring the template styles. Instead it looks like the following image:
![image](https://user-images.githubusercontent.com/33011219/44938558-1d969280-ad56-11e8-8846-edf41a9735e6.png)

This might be relevant: https://stackoverflow.com/a/14205976/1548894

**Comment by dragosct** [comment]
Hi, @e-z-t! Thank you for using our products and for this suggestion to resolve the issue. We will check the link and if the fix solution is fine, the product it will be updated with that solution. Regards, Dragos
