### ISSUE TITLE
Using fontawasome pro on sidebar

### ISSUE THREAD

**Issue by hbinduni** [creativetimofficial/ct-now-ui-dashboard-pro#46]
Hi, i trying to use `fontawesome pro` on sidebar. 
`https://fontawesome.com`

this is how i do the html code, both using `now-ui-icons` and `fontawesome`:

```
<ul class="nav">
      <li>
        <a href="/pendaftaran">
          <i class="fal fa-cog fa-fw fa-2x"></i>
          <p>Using Fontawesome</p>
        </a>
      </li>
      <li>
        <a href="../examples/charts.html">
          <i class="now-ui-icons business_chart-pie-36"></i>
          <p>Normal Now Icon</p>
        </a>
      </li>
</ul>
```

but it seem, the icon and text not align properly if i replace with `fontawesome`. below how it render on browser:

<img width="256" alt="screen shot 2018-09-09 at 10 53 17" src="https://user-images.githubusercontent.com/1378410/45260975-e5f7ac80-b41f-11e8-87b6-832b7263009b.png">

can you help to align it so it will render properly just like if we use `now-ui-icons`?

Regards,
Heri

**Comment by dragosct** [comment]
Hi, @hbinduni! Thank you for using our products. Please, see the below image and if you notice there I used the facebook icon from front awesome and it's displayed nice, so please give us your project link to see why on your project the icon it's not displayed correctly. 

<img width="244" alt="screen shot 2018-09-11 at 10 44 40" src="https://user-images.githubusercontent.com/17456857/45345750-ed4dc000-b5af-11e8-8998-99efd010965d.png">

Regards,
Dragos

**Comment by hbinduni** [comment]
Hi @dragosct10 
Thank you for your reply. I believe this issue happen when you use new js version of fontawesome pro, it will convert your `<i class="fal fa-cog></i>` into `svg` version of the fontawesome. Below the example how it render the svg:

`<li class="nav-item active"><a class="nav-link" title="Home" href="/"><svg class="svg-inline--fa fa-home fa-w-16 fa-lg fa-2x" aria-hidden="true" data-prefix="fal" data-icon="home" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M509.8 227.5L448 177.8v-76c0-3.3-2.7-6-6-6h-20c-3.3 0-6 2.7-6 6v50.1L276.1 39.1c-11.7-9.5-28.5-9.5-40.2 0L2.2 227.5c-2.6 2.1-3 5.9-.9 8.4l12.6 15.6c2.1 2.6 5.9 3 8.5.9L64 218.9v229c0 17.7 14.3 32 32 32h116c6.6 0 12-5.4 12-12V335.8l64 .3v132.2c0 6.6 5.4 12 12 12l116-.3c17.7 0 32-14.3 32-32V219l41.6 33.5c2.6 2.1 6.4 1.7 8.5-.9l12.6-15.6c2.1-2.6 1.6-6.4-.9-8.5zM416 448l-96 .3V316c0-6.6-5.4-12-12-12l-104-.3c-6.6 0-12 5.4-12 12V448H96V193.1l156.2-126c2.2-1.8 5.3-1.8 7.5 0l156.2 126V448z"></path></svg><!-- <i class="fal fa-lg fa-2x fa-home"></i> --></a></li>`

**Comment by dragosct** [comment]
Hi, @hbinduni! Why do you use the js version of the font awesome when you can just use the CSS? 

Regards,
Dragos

**Comment by hbinduni** [comment]
That is the recommendation way by fontawesome. To just apply js

**Comment by dragosct** [comment]
I understand now. In this way you must to apply css properties to align the svg near the text to the class `.svg-inline--fa`. 

Regards, 
Dragos

**Comment by hbinduni** [comment]
I try but it doesn't effect anything:

`<li [class.active]="router.url==='/'">
        <a href="/" class="align-middle">
          <i class="fal fa-tachometer fa-fw fa-2x"></i> <span class="svg-inline--fa">Dashboard</span>
        </a>
      </li>`

also, `svg-inline--fa` will automatically added into `svg` tag by `fontawesome` js

**Comment by dragosct** [comment]
Hi! Can you give us your link to the project to see how it renders the icon code in your page exactly? Regards, Dragos

**Comment by hbinduni** [comment]
Yes sure, you can check `https://beta.diparaja.com/`
on the home page, under feature section, i replace `fontawesome` `free` with `pro` version, but it show like below. The image on social media button is not correctly align.

![screen shot 2018-09-19 at 11 06 24](https://user-images.githubusercontent.com/1378410/45730527-637ba380-bbfc-11e8-9c85-b3840b054ac7.png)

**Comment by dragosct** [comment]
Hi! Please put the following properties on your class icon: 
```css
.svg-inline--fa {
    position: absolute;
    top: 50%;
    transform: translate3d(0,-50%,0);
    right: 0;
    left: 0;
    margin-right: auto;
    margin-left: auto;
}
```


Regards, 
Dragos

**Comment by hbinduni** [comment]
Thank you. It working
