### ISSUE TITLE
Modal window (notification) moves the scroll to the top

### ISSUE THREAD

**Issue by ezehnder** [creativetimofficial/ct-now-ui-dashboard-pro#47]
I've noticed that, when opening any modal window, the page scroll goes up to the top most position. Also, I'm not able to scroll back down unless I close the modal first

This issue is also happening on the demo site: 
https://demos.creative-tim.com/now-ui-dashboard-pro/examples/components/notifications.html

![image](https://user-images.githubusercontent.com/33011219/45295762-3893a000-b4d6-11e8-947b-b84c1e65518f.png)

I'm using latest version of Firefox and Chrome on Windows 10.

Thank you.
Regards.

**Comment by dragosct** [comment]
Hi, @e-z-t! To fix this issue please go in the assets/js/now-ui-dashboard.js and search the following lines: 

```js
 $('.modal').on('shown.bs.modal', function () {
       $('.main-panel').perfectScrollbar('destroy');
     }).on('hidden.bs.modal', function (){
       $('.main-panel').perfectScrollbar();
    });
```

and change with these: 

```js
    $('.modal').on('show.bs.modal', function () {
      $('.modal').perfectScrollbar();
    }).on('hidden.bs.modal', function (){
      $('.modal').perfectScrollbar('destroy');
    });
```

Regards, 
Dragos
