### ISSUE TITLE
Button outline default bootstrap color

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-now-ui-dashboard-pro#48]
Hi, if I do a buton with outline only, like `<button class="btn btn-primary btn-simple">simple</button>`, the default blue color is applying for the border when we click on it.

Example:
![simple](https://user-images.githubusercontent.com/27307704/46629012-6daf0480-cb0d-11e8-8762-4226d2053df3.PNG)

Because of that:
![style](https://user-images.githubusercontent.com/27307704/46629058-90411d80-cb0d-11e8-8a03-d18661476dc0.PNG)

Regards!

**Comment by dragosct** [comment]
Hi, @KonScyence! You are right this is a bug and to fix it please go to the assets/scss/now-ui-dashboard/mixins/buttons.scss on line 19 and add `border-color: $btn-states-color; ` like in the image below: 

![screenshot 2018-10-09 at 12 25 33](https://user-images.githubusercontent.com/17456857/46659885-7a3f6580-cbbe-11e8-883d-efa2a040bd7e.png)

After that please compile your scss and that's it. 

Regards, 
Dragos
