### ISSUE TITLE
filter-color for full page not working

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-now-ui-dashboard-pro#49]
Hi, if we want to use a full page, there is a option to personalize the filter color, but he doesn't work!

I am talking about: `filter-color="green"` in:
```
<div class="full-page login-page section-image" filter-color="green" data-image="../../assets/img/bg14.jpg">
<!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
```

Regards!

**Comment by dragosct** [comment]
Hi! Thank you for this observation you are right. To fix this please go to `assets/scss/now-ui-dashboard/_example-pages.scss` and search for the class `.full-page` and add this properties to it: 

```css
.full-page {
   min-height: 100vh;
   max-height: 999px;
}
```

After this please search inside of this class `.full-page` the following class `.full-page-background` and put the `z-index` property to value `-1`. 

The last thing you must add the filter colors at the end of the partial : 

```css
[filter-color="primary"]{
    @include linear-gradient(rgba($black-color,.20), rgba($brand-primary, 0.6));
}
[filter-color="orange"]{
    @include linear-gradient(rgba($black-color,.20), rgba($brand-warning, 0.6));
}
[filter-color="green"]{
    @include linear-gradient(rgba($black-color,.20), rgba($brand-success, 0.6));
}
[filter-color="red"]{
    @include linear-gradient(rgba($black-color,.20), rgba($brand-danger, 0.6));
}
[filter-color="blue"]{
    @include linear-gradient(rgba($black-color,.20), rgba($brand-info, 0.6));
}
```

Compile the scss and that's it. 

Regards, 
Dragos
