### ISSUE TITLE
UI bug in date picker for current date

### ISSUE THREAD

**Issue by BohdanKorinnyi** [creativetimofficial/ct-now-ui-dashboard-pro#50]
Hi, open a datepicker for current date, it has some weird element
![screenshot from 2018-10-19 15-52-04](https://user-images.githubusercontent.com/8822555/47219318-2c451180-d3b7-11e8-9ee1-aeb736798b26.png)

**Comment by dragosct** [comment]
Hi, @BohdanKorinnyi! Thank you for using our products. Please tell us which browser did you use, because we tested in chrome and firefox and everything it's working fine? 

Regards, 
Dragos

**Comment by BohdanKorinnyi** [comment]
Hi @dragosct10!
I use Google Chrome Version 69.0.3497.81 (Official Build) (64-bit), checked the issue on Ubuntu 18 and MacOS Sierra.

**Comment by dragosct** [comment]
Hi! We just test again on windows and also MacOS on chrome version 69.0.3497.100 (Official Build) (64-bit) and everything it's working fine. It's weird because I saw that also the perfect scrollbar it's not activating in your screenshot and in our site it's working fine. Did you try to remove your cache of the browser and then to try again? 

Regards, 
Dragos

**Comment by BohdanKorinnyi** [comment]
Hi, I've loaded the page in the incognito mode
![image](https://user-images.githubusercontent.com/8822555/47656344-94ee7400-db97-11e8-9ecc-ab77e0cfba6e.png)

In Firefox I don't have the problem with scrollbar but same issue happens to date time picker
OS: Ubuntu 18

**Comment by BohdanKorinnyi** [comment]
Chrome Version 69.0.3497.100 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/8822555/47672491-d7757800-dbba-11e8-8b52-32bc7987e339.png)

OS MacOS

PS: Using dev console I found out that problem is related to **.today** css class

**Comment by dragosct** [comment]
Hi, @BohdanKorinnyi! It's weird the problem. Anyway, did you fix it? Regards, Dragos

**Comment by jecht83** [comment]
I'm facing the same issue on Mac Chrome, Mac Safari, iOS and Windows.

![img_0772](https://user-images.githubusercontent.com/1212098/50387493-8cf01380-06b2-11e9-95e6-c93aeec7911e.PNG)
