### ISSUE TITLE
Minor graphical bug in input

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-now-ui-dashboard-pro#51]
Hello, as you can see below, if you use `autofocus` or if you select a data stored in the browser, the background color doesn't take the whole field.

![10507459-91ff-4cb8-9b29-8933332253b3](https://user-images.githubusercontent.com/27307704/47605921-bce4a880-d9da-11e8-9b3e-4bf7fa5587dd.png)
![c8692d91-96de-4f72-b4b7-5e9baaac7cff](https://user-images.githubusercontent.com/27307704/47605922-bce4a880-d9da-11e8-9e08-b6c84c1a3a0f.png)

Best regards,
KonScyence

**Comment by dragosct** [comment]
Hi, @KonScyence! Yes, this is happening from the browser and you have two option to solve. One will be to put the attribute `autocomplete="off"` on your input, and second it will be to add a little css from this [link](http://webagility.com/posts/remove-forced-yellow-input-background-in-chrome). 

Hope these will help you! 

Regards, 
Dragos
