### ISSUE TITLE
Doesn't work compile

### ISSUE THREAD

**Issue by bpoapps** [creativetimofficial/ct-now-ui-dashboard-pro#52]
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (E:\xampp2\htdocs\nowui\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (E:\xampp2\htdocs\nowui\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (E:\xampp2\htdocs\nowui\gulpfile.js:34:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by dragosct** [comment]
Hi, @bpoapps! Thank you for using our products. Please tell us which command did you run in your console? Regards, Dragos

**Comment by rsuard** [comment]
Hello there, 

Sorry I 'm new using SCSS, I used LESS for a few times. (But I use node and NPM for some other reasons so I understand the processes)

I followed your docu steps : 

> Download the project’s zip.
> Make sure you have node.js (https://nodejs.org/en/) installed.
> Type npm install in terminal/console in the source folder where package.json is located.
> Run in terminal gulp open-app for opening the Kit Page (default) of the product. You can set in gulpfile.js from your downloaded archive any page you want to open in browser, at line 30: gulp.src('presentation.html').
> Run in terminal gulp compile:scss for a single compilation or gulp watch for continous compilation of the changes that you make in *.scss files. This command should be run in the same folder where gulpfile.js and package.json are located.

I have some troubles at this point on my Mac : 
1- After running "npm install" in the right folder, I got some WARN (down this post)
2- Gulp is not found then  : 
`gulp open-app
-bash: gulp: command not found`
3- I tried to install gulp 4 by using npm i gulp and got some other WARN (down this post 2)

I m thinking there is some trouble with older version of gulp (deprecated) and natives, minimatch, graceful-fs .

Questions : 
How to update these ? (I tried npm i natives, npm i minimatch, npm i graceful-fs) 
Do I need to use SUDO to upgrade those ? 
Does I need to have Gulp 4 ? 
How can I install properly gulp to compile and watch SCSS ?

Thanks a lot, 
BR,

Romain 

**WARN 1 Install**
`npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> node-sass@4.12.0 install /Users/rsuard/Dropbox (FCMS)/Lab/200-Projets en cours/3DImmo-demo/material-kit-pro-html-v2.1.1/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/rsuard/.npm/node-sass/4.12.0/darwin-x64-64_binding.node

> node-sass@4.12.0 postinstall /Users/rsuard/Dropbox (FCMS)/Lab/200-Projets en cours/3DImmo-demo/material-kit-pro-html-v2.1.1/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/rsuard/Dropbox (FCMS)/Lab/200-Projets en cours/3DImmo-demo/material-kit-pro-html-v2.1.1/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN material-kit-pro@2.1.0 No repository field.
npm WARN material-kit-pro@2.1.0 license should be a valid SPDX license expression
`

**WARN 3 Gulp**
`npm i gulp
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN material-kit-pro@2.1.0 No repository field.
npm WARN material-kit-pro@2.1.0 license should be a valid SPDX license expression

+ gulp@3.9.1
updated 1 package and audited 2183 packages in 4.205s
found 7 vulnerabilities (1 low, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details`
