### ISSUE TITLE
btn bootstrap4 not all supported

### ISSUE THREAD

**Issue by marc-gist** [creativetimofficial/ct-now-ui-dashboard-pro#56]
Why doesn't the btn-light btn-dark, btn-outline-* etc work?
Please fix
thanks!

**Comment by dragosct** [comment]
Hi, @marc-gist! Thank you for using our products. Yes, we know about this problem and we will make an update these days to work that buttons. Thank you for your understanding! 

Regards,
Dragos

**Comment by marc-gist** [comment]
thank you, do you have an estimated release date? would this be covered under my support contract? or at least some of my other bug finds?

**Comment by dragosct** [comment]
Hi, @marc-gist! Today we will start to work on this update and we hope to release in one or two days. Please be more specific about what you want to say in your two last questions. 

Regards, 
Dragos

**Comment by marc-gist** [comment]
Thank you... much better, but still missing

Light and Dark (well, light is ok, but same as Secondary). Dark is secondary.

btn-outline-* broken - secondary, light, dark

**Comment by dragosct** [comment]
Hi, @marc-gist! Those colors were not in the theme from the first release, so if you want to have those colors too you can add them in your variables and then you can use them. 

Regards, 
Dragos
