### ISSUE TITLE
SweetAlert way out of date

### ISSUE THREAD

**Issue by marc-gist** [creativetimofficial/ct-now-ui-dashboard-pro#57]
Please look at updating either the SweetAlert plugin to the latest 7.33 version from your 6.9 version, as the docs/examples don't work for the version you provided, and when up manually upgraded the plugin it broke a number of CCS things that took some time to deal with.
If you don't update the plugin, please update your docs for the old syntax that the plugin uses.

so far not sure my purchase was worth it :( but I'm so far into my project with it i feel stuck. please get the plugins up to date (or docs), and Full Bootstrap 4 compatibility.

Thanks.

**Comment by dragosct** [comment]
Hi, @marc-gist! Thank you for using our products. Next week we will have an update for this product, and we will update the dependencies and other stuff. 

Thank you for your understanding! 

Regards, 
Dragos
