### ISSUE TITLE
Bootstrap 4 input groups don't work

### ISSUE THREAD

**Issue by marc-gist** [creativetimofficial/ct-now-ui-dashboard-pro#58]
https://getbootstrap.com/docs/4.0/components/input-group/ examples don't work
please update your docs to show how your template implements them with the rounded outside (which look great, but breaks the prepend and append ability.

Thanks.

**Comment by dragosct** [comment]
Hi! Sorry for the late response. You can find the documentation about this here: https://demos.creative-tim.com/now-ui-dashboard-pro/docs/1.0/components/forms.html

Regards,
Dragos

**Comment by marc-gist** [comment]
link doesnt work as its to your local dev.  docs online don't show how to prepend/append buttons, can get icons sure, but not check box, buttons, etc as per bootstrap 4.

**Comment by dragosct** [comment]
Sorry, now the link it's updated. Yes, you're are right we will update also the docs with more bs4 options in the next update. Until then you can put the code from the bs https://getbootstrap.com/docs/4.2/components/input-group/ and it will work. 

Regards, 
Dragos
