### ISSUE TITLE
PerfectScrollbar doesn't work on Linux

### ISSUE THREAD

**Issue by BohdanKorinnyi** [creativetimofficial/ct-now-ui-dashboard-pro#6]
![image](https://user-images.githubusercontent.com/8822555/35909425-39444a32-0bfc-11e8-8e94-41bbd140092b.png)

**Comment by BohdanKorinnyi** [comment]
Mini sidebar
![image](https://user-images.githubusercontent.com/8822555/35909492-7bb0dec6-0bfc-11e8-9cb7-e095f5d6d2d6.png)

**Comment by dragosct** [comment]
Hi, @BohdanKorinnyi! I just gave the solution on how to fix it. Please see #5. 

Regards,
Dragos
