### ISSUE TITLE
Sidebar scroll 

### ISSUE THREAD

**Issue by elbaylot** [creativetimofficial/ct-now-ui-dashboard-pro#61]
Hi,

I have a little problem that I can not solve despite the other issues.
When I want to see the sub-menus, the scroll bar appears but I do not want it. (I'm on the latest version 1.3.0 )

![image](https://user-images.githubusercontent.com/27012416/53370076-0e7f4e80-394d-11e9-864c-82ba73efd9ed.png)

and after : 

![image](https://user-images.githubusercontent.com/27012416/53370112-235be200-394d-11e9-891f-6e2667bb810e.png)

Thanks for your help

**Comment by dragosct** [comment]
Hi, @elbaylot! Thank you for using our products. Please go in `assets/scss/now-ui-dashboard/plugins/_plugin-perfect-scrollbar.scss` and put the code from the uploaded css file. After that you must compile the code and it will work. 

[perfect-scrollbar.css.zip](https://github.com/creativetimofficial/ct-now-ui-dashboard-pro/files/2904309/perfect-scrollbar.css.zip)

Regards,
Dragos

**Comment by elbaylot** [comment]
Thank you !
