### ISSUE TITLE
Hide logo-mini on sidebar open, keep menu open

### ISSUE THREAD

**Issue by bettinz** [creativetimofficial/ct-now-ui-dashboard-pro#62]
Hello, I'm opening this issue to ask if it's possible to hide the "mini-logo" when the mouse is hover the sidebar (so the sidebar is open) and when the bar is blocked on open.
Another question is with dropdown menus: I have 
Parent Item
->child 1
->child 2

Is it possible to keep parent item opened when i'm on child 2 page?
Thanks

**Comment by dragosct** [comment]
Hi, @bettinz! Thank you for using our products. Yes, you can put it a CSS style like this:
```css
.sidebar-mini .sidebar:hover {
    .mini-logo {
       opacity: 0
    } 
}
```
Please, can you be more specific about the second question? Do you want the dropdown to be opened after the child 2 it's pressed and redirected to the page? 

Regards,
Dragos

**Comment by bettinz** [comment]
Hello @dragosct10 , yes, something like the class="active" that highligth the menu item.
In this example I've 2 pages, called "Users", "Items".
Every page have "Add", "Edit", "Delete". So the menu is:
-Users
--Add
--Edit
--Delete

-Items
--Add
--Edit
--Delete

What I want is that when i'm in "add user" the "user" menu is already opened 😄

**Comment by bettinz** [comment]
Solved by adding `show` to `<div class="collapse`
so with `<div class="collapse show` it works 😃

**Comment by saydfuad** [comment]
If anyone needs this in the future, keep the menu open after refresh.
```
$(function () {
//Keep Main Menu open
   let activeMenu =  localStorage.getItem("activeMenu");
    if (activeMenu) {
        $(activeMenu).addClass("show");
    }
    $(document.body).on("click", "a[data-bs-target]", function (event) {
        localStorage.setItem('activeMenu', this.getAttribute("data-bs-target"));
    });
});
```
