### ISSUE TITLE
Classic modal, Notice Modal and Small alert modal doesn´t work

### ISSUE THREAD

**Issue by jposes22** [creativetimofficial/ct-now-ui-dashboard-pro#63]
Hi we try versión 1.4.0.
We update our project with this versión and modals now doesn´t work.
At first we thinks was our fail, but if you download the sources and go to:
Components>Notifications and try click on classic modal, notice modal or small alert modal on windows 10 doesn´t work with chrome or firefox.
Why doesn´t work and works fine on mac or android browsers?

We can give you some help, we detect if you remove this line at bottom modal works again:
` <script src="../../assets/js/now-ui-dashboard.min.js?v=1.4.0" type="text/javascript"></script>`
Obviously now dashboard menu on small devices doesn't work fine at all.

Can you help this bug please? 
Thank you so much!!

**Comment by dragosct** [comment]
Hi, @jposes22! Thank you for using our products. Please, tell us if you have any errors in your console when you try to open the modal. 

Regards,
Dragos

**Comment by jposes22** [comment]
> Hi, @jposes22! Thank you for using our products. Please, tell us if you have any errors in your console when you try to open the modal.
> 
> Regards,
> Dragos


Yes, 
This error happend some times but if you wait some time and press modals, stop show this errors and doesn´t work too.

![Captura](https://user-images.githubusercontent.com/4086914/58889711-a8dbf480-86e9-11e9-9ed9-5375d2b0d717.PNG)


We upload a video is better :)
https://streamable.com/3ut9j

**Comment by dragosct** [comment]
Hi! @jposes22! This error shows you that you call the perfect scrollbar, but the library it's not imported in your page, so you must put the script with the src to the library and then try again to see if now you don't have any error. 

Regards, 
Dragos

**Comment by jposes22** [comment]
> 

> scrollbar

Hi @dragosct10 ! Thats wrong, this is not our web, this its the example demo downloaded from your web. And this example has been imported perfectscrollbar, it's on line  660 ` <script src="../../assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>`

![Captura](https://user-images.githubusercontent.com/4086914/58979407-4a3c7680-87ce-11e9-9fc4-3cc2edad7cfe.PNG)

**Comment by dragosct** [comment]
Hi, @jposes22! I understand know, we will prepare an update for tomorrow of this product in order to fix that problem with the perfect scrollbar because this is the main problem. 

Thank you for your understanding! 

Regards, 
Dragos

**Comment by jposes22** [comment]
> Hi, @jposes22! I understand know, we will prepare an update for tomorrow of this product in order to fix that problem with the perfect scrollbar because this is the main problem.
> 
> Thank you for your understanding!
> 
> Regards,
> Dragos

Thanks!!

**Comment by dragosct** [comment]
The update was made. We will close the issue! 

Regards,
Dragos

**Comment by t3ppei** [comment]
im using v. 1.4.1 and modal still doesnt work...
and if i coment out:
<script src="../../assets/js/now-ui-dashboard.min.js?v=1.4.1" type="text/javascript"></script>

it works again...but the side bar now have a little scrollbar at the bottom..

console give mesage:
Error: no element is specified to initialize PerfectScrollbar             perfect-scrollbar.jquery.min.js:6:13789

**Comment by dragosct10** [comment]
Hi, @t3ppei! Thank you for using our products. Please be more specific and show us a video or something because in our part everything it's working fine! 

Regards, 
Dragos
