### ISSUE TITLE
Side Navigation overlap

### ISSUE THREAD

**Issue by Flipocap** [creativetimofficial/ct-now-ui-dashboard-pro#8]
Have a bug when I expand the side navigation.
Side navigation can then no longer be collapsed and the content disappears behind the unfolded  side navigation. Also the text overlap as seen in the picture.

<img width="882" alt="sidenav" src="https://user-images.githubusercontent.com/36418933/36112344-a65f2eda-1029-11e8-9d4b-cd3817c15380.png">

**Comment by dragosct** [comment]
Hi, @FlipB4k3r! Thank you for using our product. Please can you tell us if you made some changes in the scss? 

Regards, 
Dragos

**Comment by Flipocap** [comment]
Hi, no did not change anything. 
On the live demo, I have the same error.

Edit: Safari version 11.0.2 - no plugins
