### ISSUE TITLE
CSS does not work as expected on selectpicker with data-live-search="true" 

### ISSUE THREAD

**Issue by itcard** [creativetimofficial/ct-now-ui-dashboard-pro#9]
Thank you for this awesome template - it has a lot of great features. Would appreciate if the following bug could be resolved. The selectpicker search works but the CSS on it does not.  

![image](https://user-images.githubusercontent.com/33744833/36322826-3f5a7694-1368-11e8-80f7-4e4443b428cb.png)

**Comment by dragosct** [comment]
Hi, @itcard! Thank you for using our product. We will fix this issue in the next update which will be very soon.
 
Regards, 
Dragos
